### ISSUE TITLE
Add support for files with extentions `.hbs`, `.handlebars`, and `hbr`

### ISSUE THREAD

**Issue by Israel-Laguan** [CarlSaqui29/HandlebarsSyntaxHighlighter#18]
**Description:**

I tried this extension in VSCode to highlight my Handlebars templates, which primarily use the `.hbs` extension. However, the extension doesn't appear to recognize these files as Handlebars templates and doesn't apply syntax highlighting.

I've checked the `package.json` file of the extension, and it seems [to only specify support for the `.html` extension](https://github.com/CarlSaqui29/HandlebarsSyntaxHighlighter/blob/c9ba29a3d6380976fd7e8b3f3862d03c72c53a8c/package.json#L27). I've also tried reloading VSCode and restarting my computer to ensure everything is fresh, but the issue persists.

**Suggestion:**

I would like to suggest adding support for the following additional file extensions commonly used with Handlebars templates:

* `.hbs`
* `.handlebars`
* `.hbr`
* `.tpl`

This would greatly improve the usability of the extension for developers working with Handlebars.

**Example:**

For reference, here's a snippet of an example `.hbs` file that isn't being highlighted:

```handlebars
{{#each repositories}}
  <div>Current Branch of {{name}}: {{currentBranch}}</div>
{{~/each}}
```

I believe adding support for these extensions would be a valuable addition to the HandlebarsSyntaxHighlighter extension and benefit many developers.

**Additional Information:**

* VSCode version: 1.85.0
* Operating system: Debian 12
* HandlebarsSyntaxHighlighter version: 1.2.0 (from marketplace)

**Comment by CarlSaqui29** [comment]
Hello @Israel-Laguan! Hope you're doing well. Thank you for your suggestion. I added the support. However, for `.tpl` it needs to configured handlebars on vscode language identifier as it is used on generic extension that is often used for template files and specific language or technology associated with `.tpl` can vary.

**Comment by Israel-Laguan** [comment]
@CarlSaqui29 thanks for adding support for `.hbr` files! With that, at least for my project is fine!
